### ISSUE TITLE
Consertar detalhes e aprimorar a página de Processo de Design

### ISSUE THREAD

**Issue by gitbmvb** [Interacao-Humano-Computador/2023.1-Alistamento#36]
Observar os comentários do professor e dos monitores, fazendo os ajustes necessários na página para a entrega 2.

Autor: Danilo
Revisor: Gabriel

**Comment by Danilo-Carvalho-Antunes** [comment]
Adicionei as legendas e realizei uma descrição mais detalhada dos processos de desing
